database:
  image: mysql:5.7
  restart: always
  environment:
    - MYSQL_DATABASE=concerto
    - MYSQL_USER=concerto
    - MYSQL_PASSWORD=changeme
    - TZ=Europe/London
  volumes:
    - /home/database:/var/lib/mysql

concerto:
  image: campsych/concerto-platform:master
  restart: always
  volumes:
    - /home/concerto:/data
  environment:
    - DB_HOST=database
    - DB_PASSWORD=changeme
    - TZ=Europe/London
  links:
    - database:database
  ports:
    - "80:80"
