language: php
dist: xenial
php:
  - "7.2"

services:
  - docker
  - mysql

before_install:
  - npm install -g bower
  - composer self-update
  - mysql -e 'CREATE DATABASE concerto_test;'

install:
  - composer install --no-interaction
  - cd $TRAVIS_BUILD_DIR/src/Concerto/PanelBundle/Resources/public/angularjs && bower install --allow-root
  - cd $TRAVIS_BUILD_DIR/src/Concerto/TestBundle/Resources/public/angularjs && bower install --allow-root
  - cd $TRAVIS_BUILD_DIR
  - docker build -t campsych/concerto-platform:$TRAVIS_BRANCH .
  - docker tag campsych/concerto-platform:$TRAVIS_BRANCH campsych/concerto-platform:test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then docker tag campsych/concerto-platform:$TRAVIS_BRANCH campsych/concerto-platform:latest; fi

script: docker-compose -f ./build/travis/docker-compose.yml up --build --exit-code-from concerto

deploy:
  provider: script
  script: bash ./travis/docker_deploy.sh
  on:
    all_branches: true