parameters:
    database_driver: pdo_mysql
    env(DB_HOST): database
    env(DB_PORT): null
    env(DB_NAME): concerto
    env(DB_USER): root
    env(DB_PASSWORD): root
    database_path: null
    database_unix_socket: null
    database_version: 5.7
    test_database_name: ThisIsYourTestDatabaseName #not needed for production env
    test_database_user: ThisIsYourTestDatabaseUserName #not needed for production env
    test_database_password: ThisIsYourTestDatabaseUserPassword #not needed for production env
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en_GB
    secret: ThisTokenIsNotSoSecretChangeIt