version: '3.0'
services:
    database:
      image: mysql:5.7
      container_name: database
      restart: unless-stopped
      environment:
        - MYSQL_DATABASE=concerto
        - MYSQL_USER=concerto
        - MYSQL_PASSWORD=changeme
        - MYSQL_ROOT_PASSWORD=changeme
        - TZ=Europe/London
      volumes:
        - ./data/mysql:/var/lib/mysql

    concerto:
      image: campsych/concerto-platform:master
      container_name: concerto
      restart: unless-stopped
      volumes:
        - ./data/concerto:/data
      environment:
        - DB_HOST=database
        - DB_PASSWORD=changeme
        - TZ=Europe/London
      ports:
        - "80:80"
